#ifndef TMEDIUM_H
#define TMEDIUM_H

enum Status {VERFUEGBAR = 1, VERMIETET, REPARATUR};
enum Fahrzeugtyp {PKW = 1, LKW, WOHNWAGEN, MOTORRAD};
enum PKWTyp {KOMBI = 1, LIMOUSINE, COUPE, SPORTWAGEN, PICKUP, CABRIOLET, KLEINTRANSPORTER};
enum MotorradTyp {EBIKE = 1, MOPED, QUAD, RACEBIKE, RETRO, ROLLER};
enum WohnwagenTyp {LUXUS = 1, GEHOBEN, MITTEL, EINFACH};

#endif